#!/usr/bin/env bash
# MAAI Agent Platform — First-Run Bootstrap Script
# Usage: ./bootstrap.sh [client-name]
# Default client: default
#
# What this script does:
#   1. Validates prerequisites (Docker Compose V2, config files)
#   2. Sources client environment
#   3. Generates WEBUI_SECRET_KEY if placeholder detected
#   4. Detects GPU availability and selects ${DOCKER} compose profile
#   5. Downgrades models for CPU profile (smaller models, less VRAM)
#   6. Regenerates LiteLLM proxy_config.yaml with correct model tags
#   7. Runs LiteLLM version security check (blocks backdoored 1.82.7/1.82.8)
#   8. Starts Ollama and waits for it to be ready
#   9. Pulls all required LLM models into Ollama
#  10. Starts the full Docker Compose stack

set -euo pipefail

# ── Docker command detection (WSL/Git Bash on Windows) ───────────────────────
# Under WSL or Git Bash, native 'docker' may be a broken stub. Prefer docker.exe
# when available (Windows host Docker Desktop), fall back to native docker.
if command -v docker.exe &>/dev/null; then
  DOCKER="docker.exe"
elif command -v docker &>/dev/null; then
  DOCKER="docker"
else
  echo "[bootstrap] ERROR Docker not found. Install Docker Desktop." >&2
  exit 1
fi

# ── Constants ─────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT="${1:-default}"
ENV_FILE="${SCRIPT_DIR}/clients/${CLIENT}/client.env"
MODELS_FILE="${SCRIPT_DIR}/clients/${CLIENT}/models.yaml"
PROXY_CONFIG="${SCRIPT_DIR}/config/litellm/proxy_config.yaml"
OLLAMA_READY_TIMEOUT=120   # seconds to wait for Ollama to become ready

# ── Logging helpers ───────────────────────────────────────────────────────────
log_info()  { echo "[bootstrap] INFO  $*"; }
log_warn()  { echo "[bootstrap] WARN  $*" >&2; }
log_error() { echo "[bootstrap] ERROR $*" >&2; }

# ── Step 1: Validate prerequisites ───────────────────────────────────────────
log_info "Validating prerequisites..."

if ! ${DOCKER} compose version &>/dev/null; then
  log_error "Docker Compose V2 is required. Install Docker Desktop (which bundles it) or run:"
  log_error "  ${DOCKER} compose version"
  exit 1
fi

if [[ ! -f "${ENV_FILE}" ]]; then
  log_error "Client env file not found: ${ENV_FILE}"
  log_error "Copy from template: cp clients/${CLIENT}/client.env.example clients/${CLIENT}/client.env"
  exit 1
fi

if [[ ! -f "${MODELS_FILE}" ]]; then
  log_error "Models config not found: ${MODELS_FILE}"
  exit 1
fi

log_info "Prerequisites OK"

# ── Step 2: Source client env ─────────────────────────────────────────────────
log_info "Loading client configuration from ${ENV_FILE}..."
set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

# ── Step 3: Generate WEBUI_SECRET_KEY if placeholder ─────────────────────────
if [[ "${WEBUI_SECRET_KEY:-}" == "CHANGE_ME_RUN_BOOTSTRAP" || -z "${WEBUI_SECRET_KEY:-}" ]]; then
  log_info "Generating WEBUI_SECRET_KEY..."
  WEBUI_SECRET_KEY=$(openssl rand -hex 32)
  # Write back to client.env (cross-platform sed compatible)
  if sed --version &>/dev/null 2>&1; then
    # GNU sed (Linux)
    sed -i "s/^WEBUI_SECRET_KEY=.*/WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}/" "${ENV_FILE}"
  else
    # macOS / Git Bash sed
    sed -i '' "s/^WEBUI_SECRET_KEY=.*/WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}/" "${ENV_FILE}"
  fi
  log_info "Generated WEBUI_SECRET_KEY and saved to ${ENV_FILE}"
fi
export WEBUI_SECRET_KEY

# ── Step 4: GPU detection ─────────────────────────────────────────────────────
detect_profile() {
  if [[ "${OLLAMA_GPU_ENABLED:-true}" == "false" ]]; then
    echo "cpu"
    return
  fi
  if nvidia-smi &>/dev/null 2>&1; then
    echo "gpu"
    return
  fi
  echo "cpu"
}

PROFILE=$(detect_profile)
log_info "Detected profile: ${PROFILE}"

# ── Step 5: CPU model downgrade ───────────────────────────────────────────────
if [[ "${PROFILE}" == "cpu" ]]; then
  REASONING_MODEL="qwen2.5:7b"
  CLASSIFIER_MODEL="gemma3:1b"
  # EMBEDDING_MODEL stays as-is
  log_info "CPU profile: using smaller models (qwen2.5:7b, gemma3:1b)"
fi

# Export models so they're available for later steps
export REASONING_MODEL
export CLASSIFIER_MODEL
export EMBEDDING_MODEL

# ── Step 6: Generate proxy_config.yaml ───────────────────────────────────────
log_info "Generating LiteLLM proxy_config.yaml..."
mkdir -p "$(dirname "${PROXY_CONFIG}")"

cat > "${PROXY_CONFIG}" <<EOF
# LiteLLM Proxy Configuration
# Generated by bootstrap.sh — manual edits will be overwritten on next bootstrap run.
# Model aliases: downstream consumers use these names, never raw Ollama model tags.
model_list:
  - model_name: reasoning-model
    litellm_params:
      model: ollama_chat/${REASONING_MODEL}
      api_base: http://ollama:11434
      api_key: none
  - model_name: classifier-model
    litellm_params:
      model: ollama_chat/${CLASSIFIER_MODEL}
      api_base: http://ollama:11434
      api_key: none
  - model_name: embedding-model
    litellm_params:
      model: ollama/${EMBEDDING_MODEL}
      api_base: http://ollama:11434
      api_key: none

general_settings:
  master_key: ${LITELLM_MASTER_KEY}

litellm_settings:
  drop_params: true
  merge_reasoning_content_in_choices: true
EOF

log_info "Generated proxy_config.yaml with models: ${REASONING_MODEL}, ${CLASSIFIER_MODEL}, ${EMBEDDING_MODEL}"

# ── Step 7: LiteLLM version security check ───────────────────────────────────
# SECURITY: LiteLLM versions 1.82.7 and 1.82.8 were backdoored in a March 2026
# supply chain attack (TeamPCP / Trivy CI/CD compromise). Block those versions.
log_info "Pulling LiteLLM image and checking version..."
${DOCKER} pull ghcr.io/berriai/litellm:main-latest

LITELLM_VERSION=$(${DOCKER} run --rm ghcr.io/berriai/litellm:main-latest litellm --version 2>/dev/null || echo "unknown")
log_info "LiteLLM version: ${LITELLM_VERSION}"

if [[ "${LITELLM_VERSION}" != "unknown" ]]; then
  # Hard block: backdoored versions
  if [[ "${LITELLM_VERSION}" == "1.82.7" || "${LITELLM_VERSION}" == "1.82.8" ]]; then
    log_error "SECURITY ERROR: Backdoored LiteLLM version detected (supply chain attack, March 2026)."
    log_error "Affected version: ${LITELLM_VERSION}"
    log_error "See CLAUDE.md for details. Use litellm>=1.83.0."
    exit 1
  fi

  # Semver check: must be >= 1.83.0
  MAJOR=$(echo "${LITELLM_VERSION}" | cut -d. -f1)
  MINOR=$(echo "${LITELLM_VERSION}" | cut -d. -f2)
  PATCH=$(echo "${LITELLM_VERSION}" | cut -d. -f3 | cut -d- -f1)  # strip pre-release suffixes

  BELOW_MIN=false
  if [[ "${MAJOR}" -lt 1 ]]; then
    BELOW_MIN=true
  elif [[ "${MAJOR}" -eq 1 && "${MINOR}" -lt 82 ]]; then
    BELOW_MIN=true
  elif [[ "${MAJOR}" -eq 1 && "${MINOR}" -eq 82 && "${PATCH:-0}" -le 8 ]]; then
    BELOW_MIN=true
  elif [[ "${MAJOR}" -eq 1 && "${MINOR}" -eq 82 && "${PATCH:-0}" -gt 8 ]]; then
    # 1.82.9+ (hypothetical) would be below 1.83.0
    BELOW_MIN=true
  fi

  if [[ "${BELOW_MIN}" == "true" ]]; then
    log_error "SECURITY ERROR: LiteLLM version ${LITELLM_VERSION} is below minimum safe version 1.83.0."
    log_error "Versions 1.82.7 and 1.82.8 were backdoored in March 2026. Do not run."
    exit 1
  fi
else
  log_warn "Could not determine LiteLLM version. Proceeding — verify manually that image is >=1.83.0."
fi

# ── Step 7b: Sync host-level vars to .env for Docker Compose ─────────────────
# Docker Compose resolves ${VAR} in port mappings and environment from .env at
# the project root, NOT from env_file (which is container-only). Write the
# variables Compose needs for host-side resolution.
DOT_ENV="${SCRIPT_DIR}/.env"
cat > "${DOT_ENV}" <<EOF
CLIENT_ENV_PATH=clients/${CLIENT}/client.env
WEBUI_PORT=${WEBUI_PORT:-3000}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
EOF
log_info "Synced host variables to .env for Docker Compose"

# ── Step 8: Start Ollama and wait for ready ───────────────────────────────────
# Detect if a local Ollama is already using port 11434 — use alternate port if so
OLLAMA_PORT="${OLLAMA_PORT:-11434}"
if netstat -ano 2>/dev/null | grep -q ":${OLLAMA_PORT}.*LISTENING" || \
   ss -tln 2>/dev/null | grep -q ":${OLLAMA_PORT} "; then
  OLLAMA_PORT=11435
  log_warn "Port 11434 already in use (local Ollama?). Mapping container to host port ${OLLAMA_PORT} instead."
  log_warn "Internal service communication is unaffected (uses Docker network)."
fi
export OLLAMA_PORT
echo "OLLAMA_PORT=${OLLAMA_PORT}" >> "${DOT_ENV}"

log_info "Starting Ollama (${PROFILE} profile)..."

# Try to start only the Ollama service matching the profile; fall back to full up if needed
${DOCKER} compose --profile "${PROFILE}" up -d ollama-gpu ollama-cpu 2>/dev/null || \
  ${DOCKER} compose --profile "${PROFILE}" up -d

log_info "Waiting for Ollama to be ready (timeout: ${OLLAMA_READY_TIMEOUT}s)..."
ELAPSED=0
until ${DOCKER} exec ollama ollama list &>/dev/null 2>&1; do
  if [[ ${ELAPSED} -ge ${OLLAMA_READY_TIMEOUT} ]]; then
    log_error "Timed out waiting for Ollama after ${OLLAMA_READY_TIMEOUT}s."
    log_error "Check container logs: ${DOCKER} compose --profile ${PROFILE} logs ollama-gpu ollama-cpu"
    exit 1
  fi
  sleep 2
  ELAPSED=$((ELAPSED + 2))
done
log_info "Ollama is ready (${ELAPSED}s)"

# ── Step 9: Pull models ───────────────────────────────────────────────────────
log_info "Pulling models into Ollama..."

for MODEL in "${REASONING_MODEL}" "${CLASSIFIER_MODEL}" "${EMBEDDING_MODEL}"; do
  log_info "Pulling ${MODEL}..."
  ${DOCKER} exec ollama ollama pull "${MODEL}"
done

log_info "All models pulled"

# ── Step 10: Start full stack ─────────────────────────────────────────────────
log_info "Starting full stack..."
${DOCKER} compose --profile "${PROFILE}" up -d

log_info "Stack started successfully"
log_info ""
log_info "Access points:"
log_info "  Open WebUI: http://localhost:${WEBUI_PORT:-3000}"
log_info "  LiteLLM:    http://localhost:4000"
log_info "  Ollama:     http://localhost:${OLLAMA_PORT}"
log_info ""
log_info "To check container status:"
log_info "  ${DOCKER} compose --profile ${PROFILE} ps"
log_info ""
log_info "To view logs:"
log_info "  ${DOCKER} compose --profile ${PROFILE} logs -f"
